const Location = [
  "",
  "State Russian Museum, St. Petersburg",
  "Louvre, Paris",
  "Uffizi Gallery. Florence, Italy",
  "Kristiana (now Oslo)",
  "Rijksmuseum, Amsterdam",
  "The National Gallery, London",
  "National Museum and Munch Museum, Oslo, Norway",
  "University of Oslo, Oslo, Norway ",
  "Kunstmuseum Den Haag",
  "Florence, Private Collection, Palazzo Pucci",
  "Mauritshuis museum in The Hague, the Netherlands",
  "Sistine Chapel, Rome",
  "Museo del Prado in Madrid, Spain",
  "Gorodomlya Island, which is located on Lake Seliger",
  "Louvre Museum in Paris",
  "island of Capri, near Naples, Italy",
  "fishing village of Les Saintes-Maries-de-la-Mer",
  "Wallraf–Richartz Museum in Cologne",
  "Munch Museum (Munchmuseet) in Oslo",
  "Convent of Santa Maria delle Grazie in Milan, Italy",
  "Hermitage Museum in St. Petersburg, Russia",
  "Museum of Modern Art (MoMA) in New York City, USA",
];

export default Location;
